# Generated by Django 5.2.4 on 2025-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_supplied',
            field=models.ManyToManyField(related_name='suppliers', to='supplierHub.product'),
        ),
    ]
